const express = require('express');
const router = express.Router();
const { CartItemController } = require('../Controllers');
const { authenticate, authorize } = require('../Middlewares');
router.get('/me', authenticate, CartItemController.getMyCart);
router.get('/me/total', authenticate, CartItemController.getMyCartTotal);
router.post('/me/add', authenticate, CartItemController.addToMyCart);
router.post('/me/buy-now', authenticate, CartItemController.buyNow);
router.put('/me/product/:productId', authenticate, CartItemController.updateMyCartItem);
router.delete('/me/product/:productId', authenticate, CartItemController.removeFromMyCart);
router.delete('/me/clear', authenticate, CartItemController.clearMyCart);
router.get('/user/:userId', authenticate, authorize(1), CartItemController.getByUser);
router.get('/user/:userId/total', authenticate, authorize(1), CartItemController.getTotal);
router.get('/', authenticate, authorize(1), CartItemController.getAll);
router.get('/:id', authenticate, authorize(1), CartItemController.getById);
router.post('/', authenticate, authorize(1), CartItemController.create);
router.put('/:id', authenticate, authorize(1), CartItemController.update);
router.delete('/:id', authenticate, authorize(1), CartItemController.delete);
router.get('/admin/all', authenticate, authorize(1), CartItemController.getAllCarts);
router.get('/admin/user/:userId', authenticate, authorize(1), CartItemController.getCartByUserIdWithDetails);
router.put('/admin/item/:id', authenticate, authorize(1), CartItemController.updateCartItemByAdmin);
router.delete('/admin/item/:id', authenticate, authorize(1), CartItemController.deleteCartItemByAdmin);
router.delete('/admin/user/:userId/clear', authenticate, authorize(1), CartItemController.clearUserCartByAdmin);
router.get('/admin/statistics', authenticate, authorize(1), CartItemController.getCartStatistics);
module.exports = router;
