const express = require('express');
const router = express.Router();
const { PaymentController } = require('../Controllers');
const { authenticate, authorize, optionalAuthenticate } = require('../Middlewares');
router.get('/me', authenticate, PaymentController.getMyPayments);
router.get('/me/order/:orderId', authenticate, PaymentController.getMyPaymentByOrder);
router.post('/momo/create', authenticate, PaymentController.createMoMoPayment);
router.post('/momo/ipn', PaymentController.handleMoMoIPN);
router.post('/momo/query', authenticate, PaymentController.queryMoMoStatus);
router.get('/', authenticate, authorize(1), PaymentController.getAll);
router.get('/:id', authenticate, authorize(1), PaymentController.getById);
router.post('/', authenticate, authorize(1), PaymentController.create);
router.put('/:id', authenticate, authorize(1), PaymentController.update);
router.delete('/:id', authenticate, authorize(1), PaymentController.delete);
router.get('/order/:orderId', authenticate, authorize(1), PaymentController.getByOrder);
router.get('/gateway/:gateway', authenticate, authorize(1), PaymentController.getByGateway);
router.get('/status/:statusId', authenticate, authorize(1), PaymentController.getByStatus);
router.post('/:id/capture', authenticate, authorize(1), PaymentController.capture);
router.post('/:id/refund', authenticate, authorize(1), PaymentController.refund);
module.exports = router;
