const express = require('express');
const router = express.Router();
const { StatisticsController } = require('../Controllers');
const { authenticate, authorize } = require('../Middlewares');
router.get('/overview', authenticate, authorize(1), StatisticsController.getOverview);
router.get('/orders', authenticate, authorize(1), StatisticsController.getOrderStatistics);
router.get('/revenue', authenticate, authorize(1), StatisticsController.getRevenueStatistics);
router.get('/users', authenticate, authorize(1), StatisticsController.getUserStatistics);
router.get('/products', authenticate, authorize(1), StatisticsController.getProductStatistics);
module.exports = router;
