const express = require('express');
const router = express.Router();
const { UserController } = require('../Controllers');
const { authenticate, authorize, optionalAuthenticate } = require('../Middlewares');
router.get('/email/:email', UserController.getByEmail);
router.get('/username/:username', UserController.getByUsername);
router.get('/me', authenticate, UserController.getCurrentUser);
router.put('/me', authenticate, UserController.updateCurrentUser);
router.put('/me/profile', authenticate, UserController.updateProfile);
router.get('/', authenticate, authorize(1), UserController.getAll);
router.get('/:id', authenticate, optionalAuthenticate, UserController.getById);
router.put('/:id', authenticate, authorize(1), UserController.update); 
router.delete('/:id', authenticate, authorize(1), UserController.delete); 

router.get('/role/:roleId', authenticate, authorize(1), UserController.getByRole);
router.put('/:id/profile', authenticate, authorize(1), UserController.updateProfile);
router.put('/:id/last-login', authenticate, authorize(1), UserController.updateLastLogin);
router.put('/:id/increment-attempts', authenticate, authorize(1), UserController.incrementFailedAttempts);
router.put('/:id/reset-attempts', authenticate, authorize(1), UserController.resetFailedAttempts);
router.post('/:id/restore', authenticate, authorize(1), UserController.restore);
module.exports = router;
