module.exports = {
  errorHandler: require('./errorHandler').errorHandler,
  notFoundHandler: require('./errorHandler').notFoundHandler,
  logger: require('./errorHandler').logger,
  apiLimiter: require('./rateLimiter').apiLimiter,
  authLimiter: require('./rateLimiter').authLimiter,
  passwordResetLimiter: require('./rateLimiter').passwordResetLimiter,
  devLogger: require('./requestLogger').devLogger,
  prodLogger: require('./requestLogger').prodLogger,
  apiLogger: require('./requestLogger').apiLogger,
  validateBody: require('./requestValidator').validateBody,
  validateParams: require('./requestValidator').validateParams,
  validateQuery: require('./requestValidator').validateQuery,
  authenticate: require('./authMiddleware').authenticate,
  optionalAuthenticate: require('./authMiddleware').optionalAuthenticate,
  authorize: require('./authMiddleware').authorize,
};
